home/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('books/', views.books, name='books'),
    path('magazines', views.magazines, name='magazines'),
    path('my_checkouts/', views.my_checkouts, name='my_checkouts'),
    path('expired_checkouts/', views.expired_checkouts, name='expired_checkouts'),
]

library_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('accounts.urls')),
    path('new_material/', include('newmaterial.urls')),
    path('check_in_out/', include('check_in_out.urls')),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from newmaterial.models import Publishmaterial
from check_in_out.models import check_in_out
from datetime import timedelta
import datetime


@login_required(login_url='/accounts/login/')
def home(req):

    book_count = check_in_out.objects.filter(user=req.user, book_id__material_id__material_type='book', is_returned=False).count()
    magazine_count = check_in_out.objects.filter(user=req.user, book_id__material_id__material_type='magazine', is_returned=False).count()

    context = {
        'materials': Publishmaterial.objects.all().order_by('material_id__title'),
        'book_count': book_count,
        'magazine_count': magazine_count,
        'type': 'books or magazines',
        'response': 'Books and magazines',
    }
    return render(req, 'home.html', context)

@login_required(login_url='/accounts/login/')
def books(req):
    context = {
        # 'materials': newmaterial.objects.filter(material_type='book').order_by('-quantity_available','title'),
        'materials': Publishmaterial.objects.filter(material_id__material_type='book').order_by('material_id__title'),
        'type': 'books',
        'response': 'Books',
    }
    return render(req, 'home.html', context)

@login_required(login_url='/accounts/login/')
def magazines(req):
    context = {
        'materials': Publishmaterial.objects.filter(material_id__material_type='magazine').order_by('material_id__title'),
        'type': 'magazines',
        'response': 'Magazines'
    }
    return render(req, 'home.html', context)

@login_required(login_url='/accounts/login/')
def my_checkouts(req):

    user_loans = check_in_out.objects.filter(user=req.user, is_returned=False)

    book_count = check_in_out.objects.filter(user=req.user, book_id__material_id__material_type='book', is_returned=False).count()
    magazine_count = check_in_out.objects.filter(user=req.user, book_id__material_id__material_type='magazine', is_returned=False).count()

    context = {
        'user_loans': user_loans,
        'book_count': book_count,
        'magazine_count': magazine_count,
    }
    return render(req, 'my_checkouts.html', context)

@login_required(login_url='/accounts/login/')
def expired_checkouts(req):
    current_date = datetime.datetime.now()

    expired_material = check_in_out.objects.filter(checked_in_datetime__lt=current_date, is_returned=False).order_by('checked_in_datetime')

    context = {
        'date': datetime.datetime.now(),
        'expired_materials': expired_material,
    }
    is_user_staff = req.user.is_staff
    if is_user_staff: ### Check if user is staff member
        pass
    else:
        return HttpResponseRedirect(reverse('home:home'))

    return render(req, 'expired_checkouts.html', context)

home/templates/expired_checkouts.html
{% extends './_base.html' %}

{% block content %}

    <div class="m-2">
        <h1><b>Expired Check outs <i class="text-danger fa fa-exclamation-triangle"></i></b></h1>
        <p>{{ date.date }}</p>

        {% if expired_materials %}
            <table class="table mt-3">
                <thead>
                    <tr>
                        <th></th>
                        <th scope="col">User</th>
                        <th scope="col">Should have returned on date</th>
                        <th scope="col">Title</th>
                        <th scope="col">Time expired</th>
                    </tr>
                </thead>
                <tbody>
                    {% for expired_material in expired_materials %}
                    <tr>
                        <td>{{ expired_material.user }}</td>
                        <td>{{ expired_material.loan_return_datetime.date }}</td>
                        <td>{{ expired_material.book_id.material_id.title }}</td>
                        <td>{{ expired_material.date_diff }} days</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>There is no expired check outs</p>
        {% endif %}
    </div>


    
{% endblock %}

home/templates/home.html
{% extends './_base.html' %}

{% block content %}

    <div>
        <h1>Home</h1>
        <h4>{{ response }}</h4>
        {% if message %}
            <p>{{ message }}</p>
        {% endif %}
        <div>
            <a href="{% url 'home:home' %}">All</a>
            <a href="{% url 'home:books' %}">Books</a>
            <a href="{% url 'home:magazines' %}">Magazines</a>
        </div>

        {% if materials %}
            <table>
                <thead>
                    <tr>
                    <th scope="col"></th>
                    <th scope="col">Title</th>
                    <th scope="col">Author</th>
                    <th scope="col">Year</th>
                    <th scope="col">Language</th>
                    <th scope="col">Pages</th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for material in materials %}
                        {% if material.is_loaned %}
                            <tr class="disabled-tr" disabled>
                        {% else %}
                            <tr>
                        {% endif %}
                            {% if material.material_id.material_type == 'book' %}
                                {% if book_count == 10 %}
                                    <td><i class="fa fa-book text-white"></i></td>
                                {% else %}
                                    <td><i class="fa fa-book text-info"></i></td>
                                {% endif %}
                            {% else %}
                                {% if magazine_count == 3 %}
                                    <td><i class="fa fa-sticky-note text-white"></<i></td>
                                {% else %}
                                    <td><i class="fa fa-sticky-note text-info"></<i></td>
                                {% endif %}
                            {% endif %}
                            <td>{{ material.material_id.title }}</td>
                            <td>{{ material.material_id.author }}</td>
                            <td>{{ material.material_id.year }}</td>
                            <td>{{ material.material_id.language }}</td>
                            <td>{{ material.material_id.pages }}</td>
                            <form action="{% url 'check_out' %}" method="POST">
                            {% csrf_token %}
                                <input type="hidden" value="{{ material.material_id.id }}" name="material_data" />
                                <input type="hidden" value="{{ material.id }}" name="material_id" />
                                <td><button><i class="fa fa-plus"></i> Check out</button></td>
                            </form>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>There is no {{ type }} available.</p>
        {% endif %}
    </div>
    
{% endblock %}

home/templates/my_checkouts.html
{% extends './_base.html' %}

{% block content %}

    <div>
        <h1><b>My check outs</b></h1>
        <h4>Books: {{ book_count }}</h4>
        <h4>Magazines: {{ magazine_count }}</h4>
        {% if user_loans %}
            <table>
                <thead>
                    <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Author</th>
                    <th scope="col">Loaned on</th>
                    <th scope="col">Return no later than</th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for user_loan in user_loans %}
                        <tr>
                            <td scope="row">{{ user_loan.book_id }}</td>
                            <td>{{ user_loan.book_id.material_id.author }}</td>
                            <td>{{ user_loan.checked_out_datetime }}</td>
                            <td><b>{{ user_loan.checked_in_datetime }}</b></td>
                            <form action="{% url 'check_in' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" value="{{ user_loan.id }}" name="loan_id">
                            <td><button>Return</button></td>
                            </form>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>You have no loans at the moment.</p>
        {% endif %}
    </div>
    
{% endblock %}