accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('request_reset_password/', views.request_reset_password, name='request_reset_password'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('change_password', views.change_password, name='change_password'),
    path('logout/', views.logout, name='logout'),
    path('delete_account/', views.delete_account, name='delete_account'),
]

home/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('books/', views.books, name='books'),
    path('magazines', views.magazines, name='magazines'),
    path('my_checkouts/', views.my_checkouts, name='my_checkouts'),
    path('expired_checkouts/', views.expired_checkouts, name='expired_checkouts'),
]

library_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('accounts.urls')),
    path('new_material/', include('newmaterial.urls')),
    path('check_in_out/', include('check_in_out.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from secrets import token_urlsafe

class PasswordReset(models.Model):
    email = models.CharField(max_length=100)
    token = models.CharField(max_length=43, default=token_urlsafe)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'Active: {self.active} // {self.token}'

accounts/views.py
from django.shortcuts import render, reverse
from django.contrib.auth import authenticate, login as login_method, logout as logout_method
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from . models import PasswordReset

def login(req):

    if req.user.is_authenticated: 
        return HttpResponseRedirect(reverse('home:home'))

    context = {}
    if req.method == 'POST':
        username = req.POST['login-username']
        password = req.POST['login-password']

        user = authenticate(req, username=username, password=password)

        if user:
            login_method(req, user)
            return HttpResponseRedirect(reverse('home:home'))
        else:
            context = {
                'message': 'Username or password are incorrect.'
            }
            
    return render(req, 'login.html', context)

def logout(req):
    logout_method(req)
    return render(req, 'login.html')

def signup(req):

    if req.user.is_authenticated: 
        return HttpResponseRedirect(reverse('home:home'))

    context = {}
    if req.method == 'POST':

        firstname = req.POST['first_name']
        lastname = req.POST['last_name']
        username = req.POST['username']
        email = req.POST['email']
        password = req.POST['password']
        password_confirm = req.POST['password_confirm']

        is_staff = req.POST['is_staff']

        if password == password_confirm: 
            if User.objects.filter(username=username).exists(): 
                context = {
                    'message': 'User already exists'
                }
            else:
                if is_staff == 'staff': 
                        User.objects.create_superuser(
                            username, email, password, first_name=firstname, last_name=lastname
                        )
                        context = {
                            'message': 'Staff user has been created'
                        }
                else:
                    User.objects.create_user(
                        username, email, password, first_name=firstname, last_name=lastname
                    )
                    context = {
                        'message': 'User has been created'
                    }
        else:
            context = {
                'message': 'Passwords did not match.'
            }
    return render(req, 'signup.html', context)

def request_reset_password(req):
    context = {}
    if req.method == 'POST':
        email = req.POST['reset-email']
        is_email_valid = User.objects.filter(email=email).exists()

        if is_email_valid: 
            new_request = PasswordReset()
            new_request.email = email
            new_request.save()
            print(new_request) 
            return HttpResponseRedirect(reverse('password_reset'))

        else:
            context = {
                'message': 'The email does not exist'
            }


    return render(req, 'request_reset_password.html', context)

def password_reset(req):
    context = {}

    if req.method == 'POST':
        token = req.POST['pass-reset-token']
        email = req.POST['pass-reset-email']
        password = req.POST['pass-reset-password']
        password_confirm = req.POST['pass-reset-password-confirm']

        if password == password_confirm: 
            valid_token = PasswordReset.objects.filter(token=token, active=True).exists()
            valid_user = User.objects.filter(email=email).exists()

            if valid_token and valid_user: 
                db_token = PasswordReset.objects.get(token=token)
                db_token.active = False
                db_token.save()

                user = User.objects.get(email=email)
                user.set_password(password)
                user.save()

                context = {
                    'success_message': f'Your password has been changed!',
                    'message': False
                }
            else:
                context = {
                    'message': 'Invalid token or email.'
                }
        else:
            context = {
                'message': 'Passwords do not match.'
            }

    return render(req, 'password_reset.html', context)

def change_password(req):
    context = {}

    if req.method == 'POST':
        username = req.user.get_username()
        current_password = req.POST['change-current-password']
        new_password = req.POST['change-new-password']
        new_password_confirm = req.POST['change-new-password-confirm']

        if new_password == new_password_confirm: 
            valid_user = authenticate(req, username=username, password=current_password)
            if valid_user: 
                user = User.objects.get(username=username)
                user.set_password(new_password)
                user.save()
                context = {
                    'message': 'Your password has been updated'
                }
            else:
                context = {
                    'message': 'Current password is wrong.'
                }
        else:
            context = {
                'message': 'Your new password do not match.'
            }

    return render(req, 'change_password.html', context)

def delete_account(req):
    context = {}
    if req.method == 'POST':
        username = req.user.get_username()
        password = req.POST['delete-password']
        text_delete = req.POST['delete-confirm']
        valid_user = authenticate(req, username=username, password=password)
        if valid_user: 
            if text_delete == 'delete':
                logout_method(req)
                user = User.objects.get(username=username)
                user.delete()
                return HttpResponseRedirect(reverse('login'))
            else:
                context = {
                    'message': '\'delete\' was not typed correctly.'
                }
        else:
            context = {
                'message': 'Wrong password.'
            }

    return render(req, 'delete_account.html', context)
    

accounts/templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Library Django</title>
</head>
<body>

    {% if user.is_authenticated %}
        {% if user.is_staff %}
            <nav>
            <a href="{% url 'home:home' %}">Welcome {{ user }}!</a>
            <br/>
             <a href="{% url 'publish_material' %}"><button type="button">Publish book</button></a>
            <a href="{% url 'register_material' %}"><button type="button">Add Book</button></a>
            <div>
                <ul>
                <li>
                    <a href="{% url 'home:home' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'home:my_checkouts' %}">My check outs</a>
                </li>
                <li>
                    <a href="{% url 'home:expired_checkouts' %}">Expired check outs</a>
                </li>
                </ul>
            </div>
            </nav>
        {% else %}
            <nav>
            <a href="{% url 'home:home' %}">Hi, {{ user }}!</a>
            <button type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="navbarNav">
                <ul>
                <li>
                    <a href="{% url 'home:home' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'home:my_checkouts' %}">Checked out</a>
                </li>
                </ul>
            </div>
            </nav>
        {% endif %}
    {% endif %}

    {% block content %}



    {% endblock %}

    {% if user.is_authenticated %}
        <div>
            <div>
                <a href="{% url 'logout' %}"><button>LOG OUT</button></a>
            </div>
            <div>
                <a href="{% url 'change_password' %}">Change password</a>
            </div>
            <div>
                <a href="{% url 'delete_account' %}">Delete account</a>
            </div>
        </div>
    {% endif %}

    <script src="{% static 'js/app.js' %}"></script>
</body>
</html>

accounts/templates/change_password.html
{% extends './_base.html' %}

{% block content %}

    <div>

        <h1>Change password</h1>

        <a href="{% url 'home:home' %}">Home</a>

        <form action="{% url 'change_password' %}" method="POST">
            {% csrf_token %}
            <div class="input-pair">
                <label for="change-current-password">Type current password</label>
                <input type="password" name="change-current-password" id="change-current-password" />
            </div>
            <div class="input-pair">
                <label for="change-new-password">Type new password</label>
                <input type="password" name="change-new-password" id="change-new-password" />
            </div>
            <div class="input-pair">
                <label for="change-new-password-confirm">Confirm new password</label>
                <input type="password" name="change-new-password-confirm" id="change-new-password-confirm" />
            </div>
            <br />
            <button>Change password</button>
        </form>

        {% if message %}
            <p>{{ message }}</p>
        {% endif %}

    </div>

{% endblock %}

accounts/templates/delete_account.html
{% extends './_base.html' %}

{% block content %}

    <div>

        <h1>Delete account</h1>

        <a href="{% url 'home:home' %}">Home</a>

        <p>Are you sure you want to delete <i>{{ user }}</i>?</p>
        <p>Confirm by typing your password and '<b>delete</b>'</p>
        <form action="{% url 'delete_account' %}" method="POST">
            {% csrf_token %}
            <div>
                <label for="delete-password">Password</label>
                <input type="password" name="delete-password" id="delete-password" />
            </div>
            <div>
                <label for="delete-confirm">Type 'delete'</label>
                <input type="text" name="delete-confirm" id="delete-confirm" />
            </div>
            <br />
            <button>Delete user</button>
        </form>

        {% if message %}
            <p>{{ message }}</p>
        {% endif %}

    </div>

{% endblock %}

accounts/templates/login.html
{% extends './_base.html' %}

{% block content %}

    <div>

        <h1>Login page</h1>

        <p><a href="{% url 'signup' %}">Sign up</a></p>

        <form action="{% url 'login' %}" method="POST">
            {% csrf_token %}
            <div>
                <label for="login-username">Username</label>
                <input type="text" name="login-username" id="login-username" />
            </div>
            <div>
                <label for="login-password">Password</label>
                <input type="password" name="login-password" id="login-password" />
            </div>
            <br />
            <button>Login</button>
        </form>
        <br />
        <p>Forgot your password? <a href="{% url 'request_reset_password' %}">Reset your password</a></p>

        {% if message %}
            <p>{{ message }}</p>
        {% endif %}

    </div>

{% endblock %}

accounts/templates/password_reset.html
{% extends './_base.html' %}

{% block content %}

    <div>

        <h1>New password</h1>

        <form action="" method="POST">
            {% csrf_token %}
            <div>
                <label for="pass-reset-token">Insert token</label>
                <input type="text" name="pass-reset-token" id="pass-reset-token" />
            </div>
            <div>
                <label for="pass-reset-email">Email</label>
                <input type="email" name="pass-reset-email" id="pass-reset-email" />
            </div>
            <div>
                <label for="pass-reset-password">New password</label>
                <input type="password" name="pass-reset-password" id="pass-reset-password" />
            </div>
            <div>
                <label for="pass-reset-password-confirm">Confirm new password</label>
                <input type="password" name="pass-reset-password-confirm" id="pass-reset-password-confirm" />
            </div>
            <button>CHANGE PASSWORD</button>
        </form>

        {% if message %}
            <p>{{ message }}</p>
        {% endif %}

        {% if success_message %}
            <p>{{ success_message }}</p>
            <a href="{% url 'login' %}">Login</a>
        {% endif %}

    </div>
    
{% endblock %}

accounts/templates/request_reset_password.html
{% extends './_base.html' %}

{% block content %}

    <div>

        <h1>Reset password</h1>

        <a href="{% url 'login' %}">Login</a>

        <form action="{% url 'request_reset_password' %}" method="POST">
            {% csrf_token %}
            <div>
                <label for="reset-email">Email</label>
                <input type="email" name="reset-email" id="reset-email" />
            </div>
            <br />
            <button>new password</button>
        </form>

        {% if message %}
            <p>{{ message }}</p>
        {% endif %}

    </div>
    
{% endblock %}

accounts/templates/signup.html
{% extends './_base.html' %}

{% block content %}

    <div>

        <h1>Signup page</h1>

        <p>Already have an account? <a href="{% url 'login' %}">Login</a></p>

        <form action="{% url 'signup' %}" method="POST">
            {% csrf_token %}
            <div>
                <label for="first_name">First name</label>
                <input type="text" name="first_name" id="first_name" />
            </div>
            <div>
                <label for="last_name">Last name</label>
                <input type="text" name="last_name" id="last_name" />
            </div>
            <div>
                <label for="email">E-mail</label>
                <input type="email" name="email" id="email" />
            </div>
            <div>
                <label for="username">Username</label>
                <input type="text" name="username" id="username" />
            </div>
            <div>
                <label for="password">Password</label>
                <input type="password" name="password" id="password" />
            </div>
            <div>
                <label for="password_confirm">Confirm password</label>
                <input type="password" name="password_confirm" id="password_confirm" />
            </div>
            <div>
                <label for="is_staff">Staff</label>
                <select id="is_staff" name="is_staff" onchange="checkIfStaff(event)">
                    <option value="customer" selected>No</option>
                    <option value="staff">Yes</option>
                </select>
            </div>
            <br />
            <button>Sign up</button>
        </form>

        {% if message %}
            <p>{{ message }}</p>
        {% endif %}

    </div>

{% endblock %}